SYLLABUS = {
    "HTML": [
        "HTML Structure",
        "HTML Elements",
        "Block-level Elements",
        "Inline Elements",
        "HTML Lists",
        "Void Elements",
        "HTML Forms",
        "HTML Attributes",
        "Multiple class names as HTML attribute value",
        "Navigation within webpage",
        "Getting URLs for images",
        "Linking HTML and CSS Files",
    ],
    "CSS": [
        "CSS Properties",
        "Text Properties",
        "Background Properties",
        "Font Properties",
        "CSS Box Model",
        "CSS Flexbox",
        "CSS Media Queries",
        "CSS class selector",
        "CSS id selector",
        "CSS universal selector",
        "CSS Inheritance",
        "CSS Colors",
        "CSS Specificity and Cascade",
        "CSS Units percentage px vh vw",
        "CSS Gradients",
        "Inline Styles",
        "Reusability of CSS Rulesets",
        "Responsiveness",
    ],
    "Bootstrap": [
        "How to use Bootstrap",
        "Predefined Styles in Bootstrap",
        "Bootstrap Flexbox Properties",
        "Bootstrap Carousel",
        "Bootstrap Navbar",
        "Bootstrap Modal",
        "Bootstrap Spinner",
        "Bootstrap Containers",
        "Bootstrap Embed Utilities",
        "Bootstrap Flex Utilities",
        "Bootstrap Display Utilities",
        "Bootstrap Position Utilities",
        "Bootstrap Grid System",
        "Bootstrap Container Row Column",
        "Creating Multiple Column Layouts",
        "Column Wrapping",
        "Bootstrap Breakpoints",
        "Bootstrap Spacing Utilities",
        "Bootstrap Background Color Utilities",
        "Bootstrap Sizing Utilities",
        "Bootstrap Icons",
    ],
    "SQL / Database (SQLite, MySQL, PostgreSQL)": [
        # NOTE: Course teaches SQLite but all core SQL concepts apply equally
        # to MySQL and PostgreSQL. Treat SQLite knowledge as equivalent to
        # MySQL/PostgreSQL for SQL query and database design skills.
        "Database fundamentals",
        "Database Management System DBMS",
        "Relational Database design",
        "SQL Database Setup and Configuration",   # covers SQLite/MySQL/PostgreSQL setup
        "SQL CREATE TABLE",
        "SQL INSERT",
        "SQL SELECT",
        "SQL UPDATE",
        "SQL DELETE",
        "SQL DROP TABLE",
        "SQL ALTER TABLE",
        "Comparison Operators in SQL",
        "String Operations LIKE",
        "Logical Operators AND OR NOT",
        "IN and BETWEEN Operator",
        "ORDER BY",
        "DISTINCT",
        "Pagination LIMIT OFFSET",
        "Aggregations COUNT SUM MIN MAX AVG",
        "Alias",
        "GROUP BY",
        "GROUP BY with HAVING",
        "Expressions in SQL",
        "SQL Functions",
        "CASE Clause",
        "Set Operators",
        "Entity Relationship Modelling",
        "One-to-One Relationship",
        "One-to-Many Relationship",
        "Many-to-Many Relationship",
        "Cardinality Ratio",
        "Primary Key",
        "Foreign Key",
        "Natural JOIN",
        "Inner JOIN",
        "Left JOIN",
        "Right JOIN",
        "Full JOIN",
        "Cross JOIN",
        "Self JOIN",
        "Views",
        "Subqueries",
        "Transactions ACID Properties",
        "Indexes",
        "Connecting SQL database to Node JS",
        "SQL CRUD operations in Node JS",
    ],
    "Python": [
        "Variables and Data Types",
        "Input and Output",
        "Type Conversion",
        "String Slicing",
        "Relational Operators",
        "Logical Operators",
        "Arithmetic Operators",
        "Conditional Statements",
        "Nested Conditional Statements",
        "Loops",
        "Nested Loops",
        "Loop Control Statements",
        "Patterns",
        "String Methods",
        "Comparing Strings",
        "Rounding Numbers",
        "Floating Point",
        "Comments",
        "Lists",
        "Tuples",
        "Sets",
        "Dictionaries",
        "List Slicing",
        "Nested Lists",
        "String Formatting",
        "Functions",
        "Extended Slicing",
        "Arbitrary Function Arguments",
        "Built-in Functions abs all any reversed enumerate",
        "List Methods copy reverse",
        "Object Oriented Programming OOP",
        "Classes and Objects",
        "Attributes and Methods",
        "Inheritance",
        "Super Class and Sub Class",
        "Composition",
        "Overriding Methods",
        "Python Standard Library",
        "Modules",
        "Map Filter Reduce",
        "Scope and Namespaces",
        "Errors and Exceptions",
        "Working with Dates and Times",
        "Problem Solving",
    ],
    "JavaScript": [
        "DOM Manipulation",
        "DOM Methods and Properties",
        "DOM Events",
        "Variables",
        "Primitive Types",
        "Type Conversions",
        "String Manipulations",
        "Conditional Statements",
        "Comparison Operators",
        "Math functions Math.random Math.ceil",
        "HTML Input Element",
        "Creating HTML Elements dynamically",
        "Adding Event Listeners Dynamically",
        "Data Structures",
        "Arrays",
        "Functions",
        "Objects",
        "Object Destructuring",
        "Object Methods",
        "JavaScript Built-in Functions",
        "Local Storage",
        "Session Storage",
        "JSON",
        "JSON Methods",
        "Array Methods",
        "Callbacks",
        "Schedulers",
        "Event Listeners",
        "HTTP Methods GET POST PUT DELETE",
        "HTTP Requests using Fetch API",
        "HTTP Response Object",
        "Spread Operator",
        "Rest Parameter",
        "Template Literals",
        "Ternary Operator",
        "Switch Statement",
        "Arrow Functions",
        "Factory Function",
        "Constructor Property",
        "Instance Methods",
        "this keyword",
        "Immutable and Mutable Values",
        "Prototypal Inheritance",
        "JS Classes",
        "Inheritance in JS Classes",
        "JS Promises",
        "Async Await",
        "Synchronous and Asynchronous Execution",
    ],
    "React JS": [
        "React Components",
        "Functional Components",
        "Class Components",
        "Props",
        "Component Reusability",
        "Component Composability",
        "create-react-app",
        "Lists and Keys",
        "React Events",
        "State management in React",
        "Updating State",
        "setState",
        "Conditional Rendering",
        "Default Props",
        "UUID",
        "Component Lifecycle",
        "Mounting Phase",
        "Updating Phase",
        "Unmounting Phase",
        "React Router",
        "React Routes",
        "API Calls in React",
        "JSX",
        "Babel",
        "Fetch in React",
        "Route Props",
        "Authentication in React",
        "Authorization in React",
        "JWT Token handling in React",
        "Cookies",
        "Local Storage in React",
        "js-cookie",
        "Redirect Component",
        "withRouter",
        "Protected Route",
        "Route Parameters",
        "Integrating REST APIs in React",
        "Loading View",
        "Success View",
        "Failure View",
        "React Reconciliation",
        "Children Prop",
        "Controlled and Uncontrolled Input",
        "Props vs State",
        "React Icons",
        "React Player",
        "Recharts for data visualization",
        "React Slick",
        "React Popup",
        "React Context API",
        "Prop Drilling",
        "Context Provider",
        "Context Consumer",
        "Styled Components",
        "CSS-in-JS",
        "Debugging React",
        "React Developer Tools",
        "useState Hook",
        "useEffect Hook",
        "Making API calls with Hooks",
    ],
    "Node JS / Express JS": [
        # NOTE: Course teaches Express JS fully including middleware.
        # Express Middleware, Route Handlers, Error Handling Middleware
        # are all covered under Express JS.
        "Node JS Basics",
        "MERN Stack",
        "CommonJS Module Exports",
        "ES Module Exports",
        "Default Exports",
        "Named Exports",
        "NPM Node Package Manager",
        "Creating Node JS Project",
        "Third-party packages in Node",
        "Express JS framework",
        "Express Middleware",              # covered under Express JS
        "Custom Middleware",               # covered under Express JS
        "Logger Middleware",               # covered under Express JS
        "Authentication Middleware",       # covered under Express JS
        "Error Handling Middleware",       # covered under Express JS
        "Route Handlers in Express",
        "HTTP Server with Express",
        "Handling HTTP GET POST PUT DELETE Requests",
        "Sending HTTP Responses",
        "Sending file as HTTP Response",
        "REST API design",
        "REST API Principles",
        "RESTful routing",
        "SQLite with Node JS",
        "SQL Database connection in Node JS",
        "Database Initialization in Node JS",
        "CRUD APIs in Node JS",
        "Filtering and Searching in APIs",
        "Path Parameters in Express",
        "Query Parameters in Express",
        "Request and Response objects",
        "Environment Variables in Node JS",   # standard Node.js .env usage with dotenv
        "dotenv package",                      # covered as part of Node JS projects
        "Nodemon",
        "Debugging Node JS",
        "bcrypt Password Hashing",
        "User Registration API",
        "User Login API",
        "JWT Authentication",
        "JWT Token Generation",
        "JWT Token Verification",
        "Token-based Authentication",
        "Passing data through Middleware",
        "Get User Profile API",
        "API error handling",
        "HTTP status codes",
    ],
    "MongoDB": [
        "Introduction to MongoDB",
        "Non-Relational Databases",
        "MongoDB CRUD Operations",
        "Querying Documents in MongoDB",
        "Aggregations in MongoDB",
        "Nested Documents in MongoDB",
        "MongoDB Atlas setup",
        "Connecting MongoDB with Node JS",
    ],
    "Other": [
        "GitHub",
        "Git version control",
        "README setup",
        "Error Handling and Debugging",
        "Hosting on Render",
        "Hosting on Netlify",
        "Hosting on Vercel",
        "Code Cleanliness",
        "Best Practices",
        "API testing basics",
    ],
}

# Flat list used for LLM prompt injection
ALL_SKILLS = [skill for category in SYLLABUS.values() for skill in category]